# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Get certificates" 
  lane :certificates do
    sync_code_signing(
        type: "development",
        app_identifier: "com.hamilton.sleepsounds",
        force_for_new_devices: true,
        readonly: true
    )

    sync_code_signing(
        type: "appstore",
        app_identifier: "com.hamilton.sleepsounds",
        readonly: true
    )
  end

  desc "Generate certificates" 
  lane :generate_certificates do
    sync_code_signing(
        type: "development",
        app_identifier: "com.hamilton.sleepsounds",
        force_for_new_devices: true
    )

    sync_code_signing(
        type: "appstore",
        app_identifier: "com.hamilton.sleepsounds"
    )
  end

  desc "release"
  lane :release do
    setup_ci
    sync_code_signing(
        type: "appstore",
        app_identifier: "com.hamilton.sleepsounds",
        readonly: true
    ) 
    increment_build_number(xcodeproj: "OpenSleepSounds.xcodeproj")
    build_app(scheme: "OpenSleepSounds")
    capture_ios_screenshots(
        clean: true
    )
    app_store_connect_api_key(
        is_key_content_base64: true,
        in_house: false
    )
    deliver(
        submit_for_review: false,
        skip_metadata: true,
        skip_screenshots: false,
        skip_binary_upload: false
    )
  end
end
