# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Get certificates" 
  lane :certificates do
    sync_code_signing(
        type: "development",
        app_identifier: "com.hamilton.sleepsounds",
        force_for_new_devices: true,
        readonly: true
    )

    sync_code_signing(
        type: "appstore",
        app_identifier: "com.hamilton.sleepsounds",
        readonly: true
    )
  end

  desc "Generate certificates" 
  lane :generate_certificates do
    sync_code_signing(
        type: "development",
        app_identifier: "com.hamilton.sleepsounds",
        force_for_new_devices: true
    )

    sync_code_signing(
        type: "appstore",
        app_identifier: "com.hamilton.sleepsounds"
    )
  end

  desc "deploy"
  lane :deploy do
    setup_ci
    sync_code_signing(
        type: "appstore",
        app_identifier: "com.hamilton.sleepsounds",
        readonly: true
    )
    
    build_app(scheme: "OpenSleepSounds")

    app_store_connect_api_key(
        is_key_content_base64: true,
        in_house: false
    )
    upload_to_app_store(
        force: true,
        run_precheck_before_submit: false,
        submit_for_review: false
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "OpenSleepSounds.xcodeproj")
    build_app(scheme: "OpenSleepSounds")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
