# Uncomment the lines below you want to change by removing the # in the beginning
#The below is the correct line. However, fastlane is currently bugged - ../ and ./ both advance two directories up, whereas / gives fastlane folder.
#project '../OpenSleepSounds.xcodeproj'
#This works as a workaround.
project '/Users/jackhamilton/Documents/GitHub/Sleepsound/OpenSleepSounds.xcodeproj'

concurrent_simulators(false)
#A list of devices you want to take the screenshots from
devices([
   "iPhone 15 Pro Max",
   "iPhone 14 Plus",
   #"iPhone 8 Plus",
   "iPad Pro (12.9-inch) (6th generation)"
   #"iPhone 15",
#   "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p",
#   "Apple Watch Series 6 - 44mm"
])

app_identifier "com.hamilton.sleepsound.Snapshots"

languages([
   "en-US"
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme("Snapshot")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
